### ISSUE TITLE
Why won't the Menu appear

### ISSUE THREAD

**Issue by Tripazzy** [Tripazzy/SalsaEngine#7]
I have a scratch file which tests the engine, here is the source:

```
import salsaboy.ludo.Engine;
import salsaboy.ludo.Initializer;
import salsaboy.ludo.gameplay.GameType;
import salsaboy.ludo.graphics.Image;
import salsaboy.ludo.graphics.Window;
import salsaboy.ludo.menu.MenuItem;
import salsaboy.ludo.splash.Splash;
import java.awt.*;

class Scratch {
    private static Window frame = new Window(800, 500);
    public static void main(String[] args) {
        Engine.start(new Initializer() {
            @Override
            public GameType gameType() {
                return GameType.OTHER;
            }
    
            @Override
            public Window frame() {
                return frame;
            }
    
            @Override
            public Splash[] splashes() {
                return new Splash[0];
            }
    
            @Override
            public Color splashBackgroundColour() {
                return Color.DARK_GRAY;
            }
    
            @Override
            public String gameName() {
                return "Salsa";
            }
    
            @Override
            public Image menuBackground() {
                return null;
            }
        });
        new MenuItem("Click Me!", () -> System.out.println("Clicked"));
    }
}
```
As you can see, `new MenuItem("Click Me!", () -> System.out.println("Clicked"));` is going to add a [MenuItem](https://github.com/SalsaBoys/SalsaEngine/blob/mainmenu/src/salsaboy/ludo/menu/MenuItem.java) to the [Menu](https://github.com/SalsaBoys/SalsaEngine/blob/mainmenu/src/salsaboy/ludo/menu/Menu.java), but it only shows this:
![screen shot 2018-07-06 at 1 56 01 pm](https://user-images.githubusercontent.com/31116548/42359298-59ac0cae-8124-11e8-8dea-0547ada2c1e3.png)
without the MenuItem I added.

Can someone fix this?

**Comment by Tripazzy** [comment]
The Salsa is supposed to happen. It comes from [here](https://github.com/SalsaBoys/SalsaEngine/blob/1abb07434378a4a72a020caa4cbf20dcaacece8f/src/salsaboy/ludo/Initializer.java#L38). In the scratch you can see that it is set to Salsa which is for testing.

**Comment by TheOnlyMrCat** [comment]
Menu only iterates over the JLabels and adds then to the window when its constructor is called - only once. Put that into a function such as `Menu.refresh()` and it should work (Just remember to clear the window each time `refresh()` is called)

**Comment by Tripazzy** [comment]
wut

**Comment by Tripazzy** [comment]
What do you mean?

**Comment by TheOnlyMrCat** [comment]
Constructor from menu:

        public Menu(Image background) {
                Engine.frame.getContentPane().removeAll();
                Engine.frame.setLayout(null);
    
                try {
                    background.setBounds(new Rectangle(new Point(0, 0), new Dimension(background.getPreferredSize())));
                    Engine.frame.add(background);
                } catch (NullPointerException e) {
                    //Don't need anything here
                }
    
                int current = 0;
                for (JLabel label : options) {
                    if (current == 0) {
                        label.setBounds(new Rectangle(new Point(10, 50), label.getPreferredSize()));
                        current += 50;
                    } else {
                        label.setBounds(new Rectangle(new Point(10, 50 + current), label.getPreferredSize()));
                        current += label.getHeight();
                    }
                    System.out.println(current);
                    Engine.frame.add(label);
                }
        }

That foreach loop appears only in the constructor

**Comment by Tripazzy** [comment]
And???
Everything is supposed to show up only when you call the constructor.

**Comment by TheOnlyMrCat** [comment]
Then anything you add later doesn't show up

**Comment by Tripazzy** [comment]
Everything I add after the loop doesn't show up, that's what you're saying?

**Comment by Tripazzy** [comment]
Ohhhhhhh

**Comment by TheOnlyMrCat** [comment]
Yes

**Comment by Tripazzy** [comment]
I get it now. I didn't notice that I did the order wrong in the Scratch.

**Comment by Tripazzy** [comment]
Now the original Salsa doesn't show up.

**Comment by Tripazzy** [comment]
![screen shot 2018-07-06 at 2 11 42 pm](https://user-images.githubusercontent.com/31116548/42359642-88fecff8-8126-11e8-962f-ee9f08b22c88.png)

**Comment by Tripazzy** [comment]
Fixed by [this](https://github.com/SalsaBoys/SalsaEngine/pull/8).
